__program__ = "DoubleF"
__version__ = "0.2.1"
__author__ = "Longfei Duan"
__email__ = "duanlongfei20@mails.ucas.ac.cn"
__description__ = "A fast and flexible phase association and earthquake location method"
